server:
port: ${SERVER_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health,info,caches,metrics"
  endpoint:
    health:
      show-details: always
  metrics:
    cache:
      enabled: true

spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 0
  datasource:
    url: jdbc:postgresql://${DB_HOST:constellation-db}:5432/constellation_db?sslmode=disable&connectTimeout=10&socketTimeout=30
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

grpc:
  client:
    telemetry-service:
      address: 'static://telemetry-service:9091'
      negotiationType: PLAINTEXT